### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by anteverse** [cloudsigma/cgroupspy#13]
Hi,

It seems `cgroupspy` is not working with python 3.10 with this kind of error:
```
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

As per Python collections documentation, `Iterable` has been moved to `collections.abc` since 3.3 and left for compatibility until 3.9 included: [https://docs.python.org/3.9/library/collections.html](https://docs.python.org/3.9/library/collections.html).

A suggestion for `cgroupspy/interfaces.py`:

Replace
```python
from collections import Iterable
```

By
```python
if sys.version_info.major == 3 and sys.version_info.minor >= 3:
    from collections.abc import Iterable
else:
    from collections import Iterable
```
or equivalent in order to have a distinction between Python 3.3 and older.

**Comment by potiuk** [comment]
We have the same problem in Apache Airflow. Are there plans to implement Python 3.10 compatibility or should we look for another solution ?

**Comment by anteverse** [comment]
Thanks @cs-cruz & @potiuk

**Comment by potiuk** [comment]
Yep. just merged "unvendor" PR: https://github.com/apache/airflow/pull/22736 in Airflow 🚀
